apiVersion: v1
kind: Service
metadata:
  name: cosmic-config-server
  namespace: cosmic
spec:
  selector:
    app: cosmic-config-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31001
  type: NodePort
