apiVersion: v1
kind: Service
metadata:
  name: cosmic-usage-api
  namespace: cosmic
spec:
  selector:
    app: cosmic-usage-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31011
  type: NodePort
