apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: cosmic
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30061
  type: NodePort
