apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: internal
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30081
  type: NodePort
