apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30080
  type: NodePort
