apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-metrics-collector
  namespace: cosmic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-metrics-collector
    spec:
      containers:
      - name: cosmic-metrics-collector
        image: missioncriticalcloud/cosmic-metrics-collector
