apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-config-server
  namespace: cosmic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-config-server
    spec:
      containers:
      - name: cosmic-config-server
        image: cosmic-config-server
