apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: cosmic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry
        ports:
        - containerPort: 5000
